"""
Email Alert Agent - Sends rich HTML emails with embedded charts,
trading signals, AI analysis summaries and relevant news headlines.

Security posture:
  • Credentials NEVER stored in code or config.yaml.
  • Reads SMTP_USER and SMTP_PASSWORD from environment variables only.
  • Uses STARTTLS (port 587) by default; TLS/SSL (port 465) supported.
  • Rate-limited to avoid spamming – one digest per run.
"""
import logging
import os
import smtplib
import ssl
from datetime import datetime
from email import encoders
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any, Dict, List, Optional

from .base_agent import BaseAgent
from ..database.db_manager import DatabaseManager

logger = logging.getLogger("MarketMindAI.EmailAlertAgent")

_SIGNAL_EMOJI = {"BUY": "📈", "SELL": "📉", "HOLD": "⏸️"}
_SENTIMENT_BADGE = {
    "POSITIVE": '<span style="color:#27ae60;font-weight:bold">● POSITIVE</span>',
    "NEGATIVE": '<span style="color:#e74c3c;font-weight:bold">● NEGATIVE</span>',
    "NEUTRAL": '<span style="color:#7f8c8d;font-weight:bold">● NEUTRAL</span>',
}


class EmailAlertAgent(BaseAgent):
    """
    Composes and sends a rich HTML email digest for each analysis cycle.
    Attaches all PNG charts generated by ReportGeneratorAgent.
    """

    def __init__(self, config: Dict[str, Any], db_manager: DatabaseManager):
        super().__init__("EmailAlertAgent", config)
        self.db = db_manager

        # SMTP settings from config (non-sensitive only)
        smtp_cfg = config.get("smtp", {})
        self.host: str = smtp_cfg.get("host", "smtp.gmail.com")
        self.port: int = int(smtp_cfg.get("port", 587))
        self.use_tls: bool = smtp_cfg.get("use_tls", True)  # STARTTLS
        self.use_ssl: bool = smtp_cfg.get("use_ssl", False)  # pure SSL

        # Sensitive credentials from environment ONLY
        self.username: Optional[str] = os.getenv("SMTP_USER")
        self.password: Optional[str] = os.getenv("SMTP_PASSWORD")

        self.sender: str = smtp_cfg.get("sender", self.username or "marketmind@example.com")
        self.recipients: List[str] = smtp_cfg.get("recipients", [])
        # Optional unsubscribe URL injected per-subscriber at runtime
        self.unsubscribe_url: str = config.get("unsubscribe_url", "")
        self.app_url: str = config.get("app_url", "http://localhost:5050")

    # ── Lifecycle ──────────────────────────────────────────────────────────────

    def initialize(self) -> bool:
        if not self.username or not self.password:
            logger.warning(
                "SMTP_USER / SMTP_PASSWORD env vars not set. "
                "Email alerts will be skipped."
            )
            # Still return True so the orchestrator continues
            return True
        if not self.recipients:
            logger.warning("No email recipients configured. Email alerts will be skipped.")
            return True
        logger.info(
            f"Email Alert Agent ready – host={self.host}:{self.port} "
            f"sender={self.sender}"
        )
        return True

    def cleanup(self):
        """Cleanup resources"""
        self.logger.info("EmailAlertAgent cleanup")

    # ── Public interface ───────────────────────────────────────────────────────

    def execute(
        self,
        market_data: List[Any],
        analysis_reports: List[Any],
        signals: List[Any],
        news: List[Dict],
        chart_paths: Dict[str, List[str]],
    ) -> Dict[str, Any]:
        """
        Build and send one consolidated email digest for the current cycle.

        Returns:
            Status dict.
        """
        self.log_execution()

        if not self.username or not self.password or not self.recipients:
            logger.info("Skipping email – credentials/recipients not configured.")
            return {"status": "skipped", "reason": "credentials or recipients missing"}

        try:
            subject, html_body, all_chart_paths = self._compose_email(
                market_data, analysis_reports, signals, news, chart_paths,
                unsubscribe_url=self.unsubscribe_url,
                app_url=self.app_url,
            )
            self._send(subject, html_body, all_chart_paths)

            # Persist alert record
            self.db.save_alert({
                "symbol": "MARKET",
                "alert_type": "DIGEST",
                "subject": subject,
                "body": "HTML email sent",
                "recipients": ",".join(self.recipients),
                "sent_at": datetime.utcnow(),
                "success": True,
            })
            logger.info(f"Email digest sent to {', '.join(self.recipients)}")
            return {"status": "success", "recipients": self.recipients}

        except Exception as exc:
            logger.error(f"Failed to send email: {exc}")
            self.db.save_alert({
                "symbol": "MARKET",
                "alert_type": "DIGEST",
                "subject": "MarketMind AI Digest",
                "body": "",
                "recipients": ",".join(self.recipients),
                "sent_at": datetime.utcnow(),
                "success": False,
                "error_message": str(exc),
            })
            return {"status": "error", "error": str(exc)}

    # ── Email composition ──────────────────────────────────────────────────────

    def _compose_email(
        self,
        market_data: List[Any],
        analysis_reports: List[Any],
        signals: List[Any],
        news: List[Dict],
        chart_paths: Dict[str, List[str]],
        unsubscribe_url: str = "",
        app_url: str = "http://localhost:5050",
    ):
        now_str = datetime.now().strftime("%d %b %Y, %I:%M %p")
        subject = f"📊 MarketMind AI – Market Digest | {now_str}"

        # Build HTML sections per stock
        stock_sections_html = ""
        all_paths: List[str] = []
        cid_counter = 0

        for snapshot in market_data:
            symbol = snapshot.stock_data.symbol
            stock = snapshot.stock_data

            signal = next((s for s in signals if s.symbol == symbol), None)
            analysis = next((a for a in analysis_reports if a.symbol == symbol), None)
            stock_news = [n for n in news if n.get("symbol") == symbol][:5]
            charts = chart_paths.get(symbol, [])
            all_paths.extend(charts)

            signal_html = ""
            if signal:
                emoji = _SIGNAL_EMOJI.get(signal.signal_type, "")
                bg = {"BUY": "#e8f8e8", "SELL": "#fde8e8", "HOLD": "#fff8e1"}.get(
                    signal.signal_type, "#f0f0f0"
                )
                factors_html = "".join(
                    f"<li style='color:#27ae60'>✔ {f}</li>"
                    for f in signal.supporting_factors
                )
                risks_html = "".join(
                    f"<li style='color:#e74c3c'>✘ {r}</li>"
                    for r in signal.risk_factors
                )
                target_str = (
                    f"₹{signal.target_price:,.2f}" if signal.target_price else "N/A"
                )
                sl_str = (
                    f"₹{signal.stop_loss:,.2f}" if signal.stop_loss else "N/A"
                )
                signal_html = f"""
                <div style="background:{bg};border-radius:8px;padding:12px;margin:10px 0">
                  <h3 style="margin:0">{emoji} Signal: <strong>{signal.signal_type}</strong>
                    &nbsp;|&nbsp; Confidence: {signal.confidence_ratio:.0%}
                    &nbsp;|&nbsp; Risk: {signal.risk_level_str}
                    &nbsp;|&nbsp; Target: {target_str}
                    &nbsp;|&nbsp; Stop-Loss: {sl_str}
                  </h3>
                  <ul style="margin:6px 0">{factors_html}</ul>
                  <ul style="margin:6px 0">{risks_html}</ul>
                </div>
                """

            analysis_html = ""
            if analysis and analysis.raw_llm_response:
                snippet = analysis.raw_llm_response[:800].replace("\n", "<br>")
                analysis_html = f"""
                <div style="background:#f9f9f9;border-left:4px solid #3498db;
                            padding:10px;margin:10px 0;border-radius:4px">
                  <strong>🤖 AI Analysis:</strong><br>
                  <span style="font-size:13px;color:#333">{snippet} …</span>
                </div>
                """

            news_html = ""
            if stock_news:
                items = "".join(
                    f"""<li style="margin:4px 0">
                         {_SENTIMENT_BADGE.get(n.get('sentiment','NEUTRAL'),'')}&nbsp;
                         <a href="{n.get('url','#')}">{n.get('title','')[:120]}</a>
                         <span style="color:#888;font-size:11px">
                           — {n.get('source','')}
                         </span>
                       </li>"""
                    for n in stock_news
                )
                news_html = f"<ul style='padding-left:18px'>{items}</ul>"

            # Charts as inline images (CID)
            chart_img_html = ""
            for cpath in charts:
                cid = f"chart{cid_counter}"
                cid_counter += 1
                chart_img_html += (
                    f'<img src="cid:{cid}" style="max-width:100%;margin:6px 0;'
                    f'border-radius:6px;box-shadow:0 2px 6px rgba(0,0,0,.15)">'
                )

            change_color = "green" if stock.change_percent >= 0 else "red"
            stock_sections_html += f"""
            <div style="background:#fff;border-radius:10px;padding:16px;margin:14px 0;
                        box-shadow:0 2px 8px rgba(0,0,0,.1)">
              <h2 style="margin:0 0 8px">
                {stock.company_name} &nbsp;
                <code style="font-size:14px;color:#555">({symbol})</code>
              </h2>
              <table style="border-collapse:collapse;font-size:14px;width:100%">
                <tr>
                  <td style="padding:4px 10px"><b>Price</b></td>
                  <td>₹{stock.price:,.2f}</td>
                  <td style="padding:4px 10px"><b>Change</b></td>
                  <td style="color:{change_color}">
                    {stock.change:+.2f} ({stock.change_percent:+.2f}%)
                  </td>
                </tr>
                <tr>
                  <td style="padding:4px 10px"><b>Open</b></td>
                  <td>₹{stock.open_price:,.2f}</td>
                  <td style="padding:4px 10px"><b>High/Low</b></td>
                  <td>₹{stock.high:,.2f} / ₹{stock.low:,.2f}</td>
                </tr>
                <tr>
                  <td style="padding:4px 10px"><b>Volume</b></td>
                  <td colspan="3">{stock.volume:,}</td>
                </tr>
              </table>
              {signal_html}
              {analysis_html}
              <h4 style="margin:10px 0 4px">📰 Latest News</h4>
              {news_html or '<p style="color:#888">No recent news found.</p>'}
              {chart_img_html}
            </div>
            """

        # Build unsubscribe footer block (shown only when a token URL is available)
        if unsubscribe_url:
            unsub_block = f"""
            <div style="margin-top:24px;padding-top:14px;border-top:1px solid #ddd;
                        text-align:center;font-size:11px;color:#aaa">
              You're receiving this because you subscribed to MarketMind AI alerts.<br>
              <a href="{unsubscribe_url}"
                 style="color:#e74c3c;font-weight:bold;text-decoration:none">
                Unsubscribe in one click
              </a>
              &nbsp;|&nbsp;
              <a href="{app_url}/subscribe" style="color:#3498db;text-decoration:none">
                Manage Subscription
              </a>
            </div>"""
        else:
            unsub_block = """
            <div style="margin-top:24px;padding-top:14px;border-top:1px solid #ddd;
                        text-align:center;font-size:11px;color:#aaa">
              To unsubscribe, visit
              <a href="{app_url}/subscribe" style="color:#3498db;text-decoration:none">
                MarketMind AI Subscription Page
              </a>
            </div>""".format(app_url=app_url)

        html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;background:#f4f6f8;padding:20px;color:#222">
  <div style="max-width:780px;margin:auto">
    <div style="background:#1a1a2e;color:#fff;padding:20px;border-radius:10px;text-align:center">
      <h1 style="margin:0">📊 MarketMind AI</h1>
      <p style="margin:4px 0;color:#a0a0c0">Market Intelligence Digest — {now_str}</p>
    </div>
    {stock_sections_html}
    <div style="text-align:center;font-size:11px;color:#aaa;margin-top:16px">
      This is an automated report generated by MarketMind AI.<br>
      Not financial advice. Always do your own research.
    </div>
    {unsub_block}
  </div>
</body>
</html>"""

        return subject, html, all_paths

    # ── SMTP send ──────────────────────────────────────────────────────────────

    def _send(self, subject: str, html_body: str, chart_paths: List[str]) -> None:
        """Compose MIME message and send via SMTP."""
        msg = MIMEMultipart("related")
        msg["Subject"] = subject
        msg["From"] = self.sender
        msg["To"] = ", ".join(self.recipients)

        alternative = MIMEMultipart("alternative")
        msg.attach(alternative)
        alternative.attach(MIMEText(html_body, "html", "utf-8"))

        # Attach chart images with CID references
        for idx, path in enumerate(chart_paths):
            try:
                with open(path, "rb") as f:
                    img_data = f.read()
                img = MIMEImage(img_data, _subtype="png")
                img.add_header("Content-ID", f"<chart{idx}>")
                img.add_header(
                    "Content-Disposition", "inline",
                    filename=Path(path).name
                )
                msg.attach(img)
            except Exception as exc:
                logger.warning(f"Could not attach chart {path}: {exc}")

        context = ssl.create_default_context()

        if self.use_ssl:
            with smtplib.SMTP_SSL(self.host, self.port, context=context) as server:
                server.login(self.username, self.password)
                server.sendmail(self.sender, self.recipients, msg.as_string())
        else:
            with smtplib.SMTP(self.host, self.port) as server:
                server.ehlo()
                if self.use_tls:
                    server.starttls(context=context)
                    server.ehlo()
                server.login(self.username, self.password)
                server.sendmail(self.sender, self.recipients, msg.as_string())
